# Generated by Django 5.0.3 on 2024-04-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_likes_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
