# Generated by Django 5.0.6 on 2024-10-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_postx_liked_by_delete_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postx',
            name='hasLiked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postx',
            name='totalLikes',
            field=models.IntegerField(default=0),
        ),
    ]
