# Generated by Django 5.0.6 on 2024-10-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_postx_hasliked_postx_totallikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postx',
            name='hasLiked',
        ),
        migrations.RemoveField(
            model_name='postx',
            name='totalLikes',
        ),
    ]
