# Generated by Django 5.0.6 on 2024-10-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_remove_postx_hasliked_remove_postx_totallikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postx',
            name='totalLikes',
            field=models.IntegerField(default=0),
        ),
    ]
