# Generated by Django 5.0.6 on 2024-10-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_postx_totallikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postx',
            name='hasLiked',
            field=models.BooleanField(default=False),
        ),
    ]
