# Generated by Django 5.0.6 on 2024-10-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_postx_hasliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postx',
            name='hasLiked',
        ),
        migrations.RemoveField(
            model_name='postx',
            name='totalLikes',
        ),
    ]
