# Generated by Django 5.0.6 on 2024-10-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmodel',
            index=models.Index(fields=['receiver'], name='Home_chatmo_receive_4d10f7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmodel',
            index=models.Index(fields=['receiver', 'is_read'], name='Home_chatmo_receive_63425a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmodel',
            index=models.Index(fields=['sender'], name='Home_chatmo_sender__e373fd_idx'),
        ),
    ]
